version: 'latest'

services:
  app:
    image: app_backend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - APP_PORT=${APP_PORT}
      - APP_HOST=${APP_HOST}
      - APP_DEBUG=${APP_DEBUG}
    ports:
      - ${APP_PORT}:${APP_PORT}