name: Build and Analyze with SonarCloud

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"
  workflow_dispatch:

env:
  PY_P_DIR: RL
  MVN_P_DIR: app

permissions:
  contents: read
jobs:
  java-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "zulu"
          cache: "maven"

      - name: Load .env variables
        run: sed -e 's/\r$//' -e '/^#/d' -e '/^$/d' .env >> $GITHUB_ENV

      - name: Build and Test with Maven
        run: mvn clean verify -f ${{ env.MVN_P_DIR }}/pom.xml -Dspring.profiles.active=coverage -Pcoverage -T 4C

      - name: Save Java Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: java-coverage
          path: |
            ${{ env.MVN_P_DIR }}/target/site/jacoco/
            ${{ env.MVN_P_DIR }}/target/classes/
          retention-days: 3
  python-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install Python dependencies and Run Tests
        run: |
          pip install tox
          tox -c ./${{ env.PY_P_DIR }}/tox.ini -e py --parallel auto
      - name: Save Python Test Results
        uses: actions/upload-artifact@v4
        with:
          name: python-coverage
          path: ${{ env.PY_P_DIR }}/coverage-reports/coverage.xml
          retention-days: 3

  javascript-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run yarn and install
        run: yarn
      - name: Test and coverage
        run: yarn jest --coverage

      - name: Save JavaScript Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: javascript-coverage
          path: |
            ./coverage/lcov.info
          retention-days: 3

  sonar:
    needs: [python-tests, javascript-build, java-build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Python Coverage Report
        uses: actions/download-artifact@v4
        with:
          name: python-coverage
          path: ${{ env.PY_P_DIR }}/coverage-reports/

      - name: Download JavaScript Coverage Report
        uses: actions/download-artifact@v4
        with:
          name: javascript-coverage
          path: ./${{ env.PY_P_DIR }}/coverage/

      - name: Download Java Coverage Report
        uses: actions/download-artifact@v4
        with:
          name: java-coverage
          path: ${{ env.MVN_P_DIR }}/target/

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
